version: '3'
services:
  docker-backend:
    build:
      context: .
      dockerfile: Docker/backendDoc/Dockerfile
    image: backend-doc:latest
    container_name: backend-container
    ports:
      - 3000:3000
  docker-frontend:
    build:
     context: .
     dockerfile: Docker\frontendDoc\Dockerfile
    image: frontend-doc:latest
    container_name: frontend-container
    ports:
      - 4200:80
